/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Message {
  id: string;
  message: string;
  recipient_id: string;
  sender_id: string;
}
