networks:
  mynetwork:
services:
  api:
    container_name: API
    env_file: ".env"
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "${DOCKER_API_PORT}:80"
    networks:
      - mynetwork
    
  
  ui:
    build:
      context: ../
      dockerfile: ./docker/ui/Dockerfile
    ports:
      - "${DOCKER_UI_MIN_PORT}-${DOCKER_UI_MAX_PORT}:4200"
    deploy:
      mode: replicated
      replicas: "${DOCKER_UI_COUNT}"
    networks:
      - mynetwork