services:
  rest-cont:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 80
    deploy:
      mode: replicated
      replicas: 1
  
  ui-cont:
    build:
      context: ../
      dockerfile: ./docker/ui/Dockerfile
    ports:
      - 4200
    deploy:
      mode: replicated
      replicas: 2