/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyLoginForAccessTokenTokenPost } from '../../models/body-login-for-access-token-token-post';
import { Token } from '../../models/token';

export interface LoginForAccessTokenTokenPost$Params {
      body: BodyLoginForAccessTokenTokenPost
}

export function loginForAccessTokenTokenPost(http: HttpClient, rootUrl: string, params: LoginForAccessTokenTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Token>> {
  const rb = new RequestBuilder(rootUrl, loginForAccessTokenTokenPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Token>;
    })
  );
}

loginForAccessTokenTokenPost.PATH = '/token';
